// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxmyqllttwmgvkvogdki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4bXlxbGx0dHdtZ3Zrdm9nZGtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDI4OTcsImV4cCI6MjA2MzkxODg5N30.zBlSuSITlBziBXZcqieDOTOSQwLFWhFHvWBnhO6SADw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);